;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        org-delete-char
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        prelude-move-beginning-of-line
        skeleton-pair-insert-maybe
        ))

(setq mc/cmds-to-run-once
      '(
        crux-move-beginning-of-line
        mouse-set-region
        org-ctrl-c-ctrl-c
        which-key-C-h-dispatch
        ))
